[package]
name = "pb_test_buttons"
version = "0.1.0"
authors = ["Tortus-exe <65506144+Tortus-exe@users.noreply.github.com>"]
edition = "2024"
# resolver = "2"
rust-version = "1.88"

[[bin]]
name = "pb_test_buttons"
path = "./src/main.rs"
# harness = false # do not use the built-in cargo test harness -> resolve rust-analyzer errors

[profile.release]
# opt-level = 3
codegen-units = 1 # LLVM can perform better optimizations using a single thread
debug = 2
lto = "fat"
opt-level = "s"

[profile.dev]
debug = true    # Symbols are nice, and they don't increase the size on Flash
opt-level = 3 # "s"

[features]
# default = []
ILI = []
ST = []
# sim = []

[dependencies]
log = "0.4"
button_idf = { path = "./button_idf" }
rotenc = { path = "./rotenc" }
anyhow = { version = "1.0.100", default-features = false }
ledc = { path = "./ledc" }
pwm = { path = "./pwm" }
wifi = { path = "./wifi" }
global_settings = { path = "./global_settings" }
fontfile = { path = "./fontfile" }
flash_storage = { path = "./flash_storage" }
# ilidriver = { path = "./ilidriver" }
embedded-graphics = "0.8.2"
ili9341 = "0.6.0"
display-interface-spi = "0.5.0"
# st7735-lcd = { git = "https://github.com/sajattack/st7735-lcd-rs.git", branch = "misc-improvements", version = "0.10.0" }
st7735-lcd = { path = "./st7735-lcd-rs", features = ["graphics"] }
menus = { path = "./menus" }
embassy-executor = { version = "0.10.0", features = ["log"] }
# littlefs2 = { version = "0.8.0", features = ["alloc", "c-stubs"] }
littlefs2 = { git = "https://github.com/Tortus-exe/littlefs2.git", features = ["alloc", "c-stubs"] }
embedded-hal-bus = "0.3.0"
static_cell = "2.1.1"
critical-section = "1.2.0"
dummy-pin = "1.0.0"
esp-hal = { version = "1.1.1", features = ["esp32s3", "log-04", "unstable"] }
esp-rtos = { version = "0.3.0", features = ["embassy", "esp32s3", "esp-alloc", "esp-radio", "log-04"] }
esp-bootloader-esp-idf = { version = "0.5.0", features = ["esp32s3", "log-04"] }
esp-alloc = { version = "0.10.0", features = ["esp32s3", "nightly"] }
esp-backtrace = { version = "0.19.0", features = ["esp32s3", "panic-handler", "println"] }
esp-println = { version = "0.17.0", features = ["esp32s3", "log-04"] }
esp-radio = { version = "1.0.0-beta.0", features = ["esp32s3", "esp-alloc", "log-04", "unstable", "wifi"] }

embedded-io = "0.7.1"
embedded-io-async = "0.7.0"
embassy-net = { version = "0.9.1", features = [
  "dhcpv4",
  "log",
  "medium-ethernet",
  "tcp",
  "udp",
] }
embassy-time = { version = "0.5.0", features = ["log"] }
embassy-sync = "0.8.0"
embedded-hal = "1.0.0"
embassy-futures = "0.1.2"
