[package]
name = "menus"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
fontfile = { path = "../fontfile" }
log = "0.4.29"
global_settings = { path = "../global_settings" }
embedded-graphics = "0.8.2"
display-interface-spi = "0.5.0"
embedded-graphics-simulator = "0.8.0"

[target.'cfg(target_os = "espidf")'.dependencies]
esp-idf-hal = "0.45.2"
ledc = { path = "../ledc" }
rotenc = { path = "../rotenc" }
pwm = { path = "../pwm" }
button_idf = { path = "../button_idf" }
ili9341 = "0.6.0"
st7735-lcd = { path = "../st7735-lcd-rs" }

[target.'cfg(not(target_os = "espidf"))'.dependencies]
embedded-graphics-simulator = "0.8.0"
