//! Button IDF is in charge of doing the debouncing of buttons and things.
//!
//! This library was generated by Qwen. 


#![no_std]   // ESP‑32 builds are no‑std; remove if you use std
#![no_main]  // If you build a full application

extern crate alloc;

use esp_hal::gpio::{InputConfig, Pull, Input, AnyPin, Pin};
use esp_hal::time::Instant;
use esp_hal::delay::Delay;
use embedded_hal::delay::DelayNs;
use embassy_executor::Spawner;
use embassy_sync::channel::{Channel, Receiver};
use embassy_sync::blocking_mutex::raw::CriticalSectionRawMutex;
use alloc::boxed::Box;
use alloc::vec::Vec;
use alloc::fmt;

// ---------------------------------------------------------------------------
// Configuration – feel free to change / make these const generics
// ---------------------------------------------------------------------------
const LONG_PRESS_DURATION_MS: u64 = 2000;          // default: 2 s
const LONG_PRESS_REPEAT_MS:   u64 = 50;            // default: 50 ms
const CHANNEL_BUFFER_SIZE: usize  = 10;

// ---------------------------------------------------------------------------
// Public API – event types
// ---------------------------------------------------------------------------

/// represents the state of a single button.
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
#[repr(u8)]
pub enum ButtonEventKind {
    Down = 1,
    Up   = 2,
    Held = 3,
}

/// represents a single button event. `pin` is the pin number the button is associated with, and
/// `event` is the state of the button (whether it was pressed down this tick, let go this tick, or
/// held down.)
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub struct ButtonEvent {
    pub pin:   i32,
    pub event: ButtonEventKind,
}

impl fmt::Display for ButtonEvent {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self.event {
            ButtonEventKind::Down => write!(f, "({}, Down)", self.pin),
            ButtonEventKind::Up => write!(f, "({}, Up)", self.pin),
            ButtonEventKind::Held => write!(f, "({}, Held)", self.pin),
        }
    }
}

// ---------------------------------------------------------------------------
// Debounce state
// ---------------------------------------------------------------------------

// used for the convolution inside the debouncer
const MASK: u16 = 0b1111000000111111;

/// This is the debouncing state machine. Create one debouncing state machine per pin.
/// `Debounce::update_button` should be called every tick.
struct Debounce<'a> {
    inverted:   bool,
    history:    u16,
    down_time:  u64,
    next_long_time: u64,
    pin: Box<Input<'a>>,
    pintype: i32, // TODO: make this a proper enum
}

impl Debounce<'_> {
    /// Updates the state of the button. Should be called every tick.
    fn update_button(&mut self) {
        // level: 1 = high, 0 = low
        let level = self.pin.is_high();
        self.history = (self.history << 1) | if level { 1 } else { 0 };
    }

    /// Polls the button to see if it has risen this tick.
    fn button_rose(&mut self) -> bool {
        if (self.history & MASK) == 0b0000000000111111 {
            self.history = 0xffff;
            true
        } else {
            false
        }
    }

    /// Polls the button to see if it has fallen this tick.
    fn button_fell(&mut self) -> bool {
        if (self.history & MASK) == 0b1111000000000000 {
            self.history = 0x0000;
            true
        } else {
            false
        }
    }

    /// polls the button to see if it has been pressed down this tick.
    fn button_down(&mut self) -> bool {
        if self.inverted { self.button_fell() } else { self.button_rose() }
    }

    /// polls the button to see if it has been released up this tick.
    fn button_up(&mut self) -> bool {
        if self.inverted { self.button_rose() } else { self.button_fell() }
    }
}

// ---------------------------------------------------------------------------
// Helper – create an input pin from a pin number
// ---------------------------------------------------------------------------
// Creates a configured input pin from a pin number.
// The function uses a large `match` because the HAL uses type‑level pins
// – the same code pattern is repeated for all 40 GPIOs on the ESP‑32.
// fn create_input_pin(
//     gpio:     &mut Gpio,
//     pin_no:   u8,
//     pull_mode: PullMode,
// ) -> Result<Box<PinDriver<AnyIOPin, Input>>, EspError> {
//     use PullMode as HalPull;

//     let pin_obj = PinDriver::input(gpio, )

//     Ok(pin_obj)
// }

// ---------------------------------------------------------------------------
// Public entry points – mirroring button_init / pulled_button_init
// ---------------------------------------------------------------------------

#[embassy_executor::task]
async fn listen_button(mut debounces: Vec<Debounce<'static>>) {
    // let timer = TimerDriver::new(timerg, &TimerConfig::new()).unwrap();
    let instant = Instant::now();
    let mut delay = Delay::new();
    let event_sender = CHANNEL.sender();
    loop {
        // let time = timer.counter().unwrap();
        // let now_ms = (1000 * time) / timer.tick_hz();
        let now_ms = instant.duration_since_epoch().as_millis();

        for d in debounces.iter_mut() {
            d.update_button();

            if d.button_up() {
                d.down_time = 0;
                let ev = ButtonEvent { pin: d.pintype, event: ButtonEventKind::Up };
                // let _ = queue_task.push(ev.into());
                event_sender.send(ev).await;
            } else if d.down_time != 0 && now_ms >= d.next_long_time {
                let ev = ButtonEvent { pin: d.pintype, event: ButtonEventKind::Held };
                // let _ = queue_task.push(ev.into());
                event_sender.send(ev).await;
                d.next_long_time += LONG_PRESS_REPEAT_MS;
            } else if d.button_down() && d.down_time == 0 {
                d.down_time = now_ms;
                d.next_long_time = now_ms + LONG_PRESS_DURATION_MS;
                let ev = ButtonEvent { pin: d.pintype, event: ButtonEventKind::Down };
                event_sender.send(ev).await;
                // let _ = queue_task.push(ev.into());
            }
        }

        // 10 ms delay – same as the original 10 / portTICK_PERIOD_MS
        // esp_idf_hal::delay::FreeRtos::delay_ms(10);
        delay.delay_ms(1000 as u32);
    }
}

static CHANNEL: Channel<CriticalSectionRawMutex, ButtonEvent, CHANNEL_BUFFER_SIZE> = Channel::<CriticalSectionRawMutex, ButtonEvent, CHANNEL_BUFFER_SIZE>::new();

/// Creates a new thread that starts polling the buttons and updating the debouncer. The thread
/// will initialize all buttons in `pin_select`, then regularly poll their state. 
/// It will send events out via `queue`.
pub fn button_init(
    pin_select: Vec<AnyPin<'static>>,
    spawner: Spawner,
    // queue: ,
) -> Receiver<'static, CriticalSectionRawMutex, ButtonEvent, CHANNEL_BUFFER_SIZE>
    // where T: From<ButtonEvent> + Copy + Send + Sync + 'static
{
    // 1️⃣  Grab the peripherals
    // let peripherals = Peripherals::take()
    //     .or_else(|_| Err(EspError::from_non_zero(NonZero::new(0x103))))?;
    // let mut gpio = peripherals.gpio;

    // 2️⃣  Count the pins (used only for pre‑allocating the vector)
    // let pin_count = pin_select.count_ones() as usize;

    // 3️⃣  Build the debounce list
    let mut debounces: Vec<Debounce> = Vec::with_capacity(pin_select.len());
    for pin in pin_select {
        // pin.set_pull(Pull::Down)?;
        let pin_number: i32 = pin.number() as i32;
        let pin_obj = Input::new(pin, InputConfig::default().with_pull(Pull::Up));
        debounces.push(Debounce {
            inverted:      true,              // active‑low buttons
            history:       0xffff,            // start with all bits set
            down_time:     0,
            next_long_time:0,
            pin:           Box::new(pin_obj),
            pintype:       pin_number,
        });
    }

    // 4️⃣  Create the event queue
    // let queue: Arc<Queue<ButtonEvent>> = Arc::new(Queue::new(QUEUE_SIZE));
    // let queue_task = queue.clone();            // clone for the task

    // 5️⃣  Create a timer for millis() – internally uses esp_timer
    // let timer = Timer::new();

    // 6️⃣  Spawn the background task
    // Task::new()
    //     .stack_size(TASK_STACK_SIZE)
    //     .priority(10)                // priority 10 = normal
    let _ = spawner.spawn(listen_button(debounces).unwrap());   // propagate any spawn error

    // 7  Return the queue to the caller
    CHANNEL.receiver()
}
