[package]
name = "flash_storage"
version = "0.1.0"
edition = "2024"

[dependencies]
embedded-storage = "0.3.1"
esp-hal = { version = "1.1.1", features = ["esp32s3"] }
esp-storage = { version = "0.9.0", features = ["esp32s3", "critical-section"] }
littlefs2 = "0.8.0"
log = "0.4.33"

[profile.dev.package.esp-storage]
opt-level = 3
